In [1]:
import sys
import numpy as np

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [4]:
#Agisnaciones para arrays

a = np.array([1, 2, 3, 4])
b = np.array([0, .5, 1, 1.5, 2])


In [5]:
a[0], a[1]

(1, 2)

In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[1:-1]

array([2, 3])

In [9]:
a[::2]

array([1, 3])

In [10]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [11]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [12]:
b[[0, 2, -1]]

array([0., 1., 2.])

In [13]:
#Types NumPy

In [14]:
a

array([1, 2, 3, 4])

In [16]:
a.dtype

dtype('int32')

In [17]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [18]:
b.dtype

dtype('float64')

In [19]:
np.array([1, 2, 3, 4], dtype=np.float)

array([1., 2., 3., 4.])

In [20]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [21]:
c = np.array(['a', 'b', 'c'])

In [22]:
c.dtype

dtype('<U1')

In [23]:
d = np.array([{'a': 1}, sys])

In [24]:
d.dtype

dtype('O')

In [25]:
#Dimensions

In [26]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])


In [27]:
A.shape

(2, 3)

In [28]:
A.size

6

In [29]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [30]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [31]:
B.shape

(2, 2, 3)

In [32]:
B.ndim

3

In [33]:
B.size

12

In [34]:
#Indexing and Slicing of Matrices

In [35]:
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [36]:
A[1]

array([4, 5, 6])

In [37]:
A[1][0]

4

In [38]:
A[1, 0]

4

In [39]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [41]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [42]:
A[:2, 2:]

array([[3],
       [6]])

In [43]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
A[1] = np.array([10, 10, 10])

In [45]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [47]:
A[2] = 99

In [48]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [49]:
#statistics

In [50]:
a = np.array([1, 2, 3, 4])

In [51]:
a.sum()

10

In [52]:
a.mean()

2.5

In [53]:
a.std()

1.118033988749895

In [54]:
a.var()

1.25

In [55]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [56]:
A.sum()

45

In [57]:
A.mean()

5.0

In [58]:
A.std()

2.581988897471611

In [59]:
A.sum(axis=0)

array([12, 15, 18])

In [60]:
A.sum(axis=1)

array([ 6, 15, 24])

In [61]:
A.mean(axis=0)

array([4., 5., 6.])

In [62]:
A.mean(axis=1)

array([2., 5., 8.])

In [63]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [64]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [65]:
# Here there are more methods: https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#array-methods

In [66]:
#Broadcasting and Vectorized operations

In [67]:
a = np.arange(4)

In [68]:
a

array([0, 1, 2, 3])

In [69]:
a + 10

array([10, 11, 12, 13])

In [70]:
a * 10

array([ 0, 10, 20, 30])

In [71]:
a

array([0, 1, 2, 3])

In [72]:
a += 100

In [73]:
a

array([100, 101, 102, 103])

In [74]:
l = [0, 1, 2, 3]

In [75]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [76]:
a = np.arange(4)

In [77]:
a

array([0, 1, 2, 3])

In [78]:
b = np.array([10, 10, 10, 10])

In [79]:
b

array([10, 10, 10, 10])

In [80]:
a + b

array([10, 11, 12, 13])

In [81]:
a * b

array([ 0, 10, 20, 30])

In [82]:
# Boolean arrays

In [83]:
a = np.arange(4)

In [84]:
a

array([0, 1, 2, 3])

In [85]:
a[0], a[-1]

(0, 3)

In [86]:
a[[0, -1]]

array([0, 3])

In [87]:
a[[True, False, False, True]]

array([0, 3])

In [88]:
a

array([0, 1, 2, 3])

In [89]:
a >= 2

array([False, False,  True,  True])

In [90]:
a[a >= 2]

array([2, 3])

In [91]:
a.mean()

1.5

In [92]:
a[a > a.mean()]

array([2, 3])

In [93]:
a[~(a > a.mean())]

array([0, 1])

In [94]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [95]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [96]:
A = np.random.randint(100, size=(3, 3))

In [97]:
A

array([[ 1, 80, 91],
       [13, 43, 43],
       [75, 90, 45]])

In [98]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([ 1, 91, 43, 75, 45])

In [99]:
A > 30

array([[False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [100]:
A[A > 30]

array([80, 91, 43, 43, 75, 90, 45])

In [101]:
#Linear Algebra

In [102]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [103]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [104]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [105]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [106]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [107]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [108]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])